### ISSUE TITLE
Possible enhancement - power saving?

### ISSUE THREAD

**Issue by ac1176** [lrswss/esp8266-wifi-power-meter#9]
Hi Lars,

Thanks for the effort you've gone to with this little project. I stumbled across it a few weeks ago while I was researching the possibility of reading my old spinning disc energy meters at my house and logging my energy usage. I was pleasantly surprised when your code just worked straight away without any further intervention on my part. A lot of the other projects for reading electromechanical meters I'd seen thus far seemed to require a significant amount of fine-tuning and careful planning in order for the meter to read correctly, and yours is the first one which worked first time around, which I'm really grateful for!

I was wondering if you were considering adding any form of power saving features to the ESP8266 codebase? I realise that the ESP8266 doesn't have a great deal of flexibility in terms of allowing A/D reads while in sleep, and that the very nature of the meter reads means that the CPU cannot be allowed to sleep in between pulses. But perhaps there could be an option to disable the Wifi for a period, continue to detect/count pulses in that period (with timestamps) and then enable Wifi long enough to transmit a burst of logged data for that period to MQTT? Maybe the web interface could have a selectable 'power saving' option which allows the user to specify a period of 'Wifi disabled' in minutes/hours?

My initial test setup for trying out your project was powered by a single 18650 cell, which initially worked great but didn't last overnight. My hope was that I could use a small solar cell to keep the battery topped up during the day and rely on the battery at night, or when daytime solar levels are low.

Thanks again for your work on this project!

**Comment by lrswss** [comment]
I have done some tests lately. When Wifi is off, the ESP8266 power consumption drops from 78mA to about 24mA. Reducing the CPU speed from 160MHz to 80MHz helps to get close to 19mA. This is more or less consistent with what I have read in various articles on the internet. But I guess that's still quite a lot to run the Wifi power meter on a (single) 18650 cell. Using a 3000mAh cell would probably provide enough power for about 5-6 days. The only way to noticeably reduce power consumption (< 1 mA) is to use deep sleep mode, which is surely not practical for this application. 

What do you think, are 19mA worth the effort to introduce a (simple) "power save mode"? Switching on Wifi, publishing data und turning off Wifi takes barely one second. Of course, the latter would also make the web interface inaccessible, since the ESP8266 only wakes up to transmit the data via MQTT. However, the power save mode could be turned off with a MQTT command topic.

To keep things simple I'd rather not implement a data backlog with timestamps...

**Comment by ac1176** [comment]
> What do you think, are 19mA worth the effort to introduce a (simple) "power save mode"? Switching on Wifi, publishing data und turning off Wifi takes barely one second. Of course, the latter would also make the web interface inaccessible, since the ESP8266 only wakes up to transmit the data via MQTT. 

Your test results for power consumption with and without WiFi align with what I've seen as well. A saving of three-quarters may be attractive for users who may want to use battery power.

> However, the power save mode could be turned off with a MQTT command topic.

Another possibility is that the power saving mode could be disabled using a GPIO pin. The user could install a jumper on the ESP board, or use an external switch or relay any time they want to have the WiFi activated on demand. That would allow the web interface to remain open if the user wants to log in to view metering data or make setting changes.

> To keep things simple I'd rather not implement a data backlog with timestamps...

Understood. I can see that is probably more work than it's worth in this scenario.

Having said all that, unfortunately my electricity provider has since advised me that my Ferraris meters are soon to be replaced with new smart meters which only provide pulsing LED outputs. I'm happy to do some testing for you if you feel modifying the code is something you'd like to pursue, but I fear opportunities for me to do so will soon dry up.

**Comment by lrswss** [comment]
Added a power saving mode with the most recent release. The consumption of the Wifi Power Meter was reduced from 95mA to about 35mA (20mA ESP8266, 15mA TCRT5000). I had to take a few turns to deal with the unexpected change in ADC readings if ESP8266's WiFi is switched off. I'd be happy if you could give it a try.
